import type { ThemeDefinition } from '../types'

/**
 * Glass Industrial 亮色 — 浅色工业风。
 */
export const glassIndustrialLight: ThemeDefinition = {
  id: 'glass-industrial-light',
  name: 'Glass Industrial 亮色',
  description: '浅色工业风（亮色），带毛玻璃和圆角',
  isDark: false,
  tokens: {
    '--bg': '#f4f6fa',
    '--bg-panel': '#ffffff',
    '--bg-elevated': '#eef2f8',
    '--border': '#d8dee6',
    '--text': '#0f172a',
    '--text-dim': '#64748b',
    '--accent': '#2563eb',
    '--accent-cyan': '#0891b2',
    '--accent-teal': '#0d9488',
    '--rx-bg': 'rgba(59, 130, 246, 0.08)',
    '--rx-border': 'rgba(59, 130, 246, 0.25)',
    '--rx-text': '#0f172a',
    '--tx-bg': 'rgba(16, 185, 129, 0.08)',
    '--tx-border': 'rgba(16, 185, 129, 0.25)',
    '--tx-text': '#0f172a',
    '--ok': '#16a34a',
    '--warn': '#d97706',
    '--err': '#dc2626',
    '--search-highlight-bg': '#fde047',
    '--search-highlight-text': '#0f172a',
    '--search-active-bg': '#f59e0b',
    '--search-active-text': '#0f172a',
    '--glass-bg': 'rgba(255, 255, 255, 0.72)',
    '--glass-border': 'rgba(15, 23, 42, 0.08)',
    '--glass-highlight': 'rgba(255, 255, 255, 0.95)',
    '--glass-blur': '12px',
    '--glass-blur-sm': '8px',
    '--shadow-sm': '0 1px 3px rgba(15, 23, 42, 0.06), 0 1px 2px rgba(15, 23, 42, 0.04)',
    '--shadow-md': '0 4px 12px rgba(15, 23, 42, 0.08), 0 2px 4px rgba(15, 23, 42, 0.04)',
    '--shadow-lg': '0 10px 25px rgba(15, 23, 42, 0.10), 0 4px 10px rgba(15, 23, 42, 0.05)',
    '--radius': '6px',
    '--radius-sm': '4px',
    '--radius-md': '6px',
    '--radius-lg': '8px',
    '--radius-xl': '10px',
    '--gap': '8px',
    '--mono-font': "'JetBrains Mono', 'Cascadia Mono', 'Consolas', 'Menlo', monospace",
    '--ui-font': "'Inter', -apple-system, 'Segoe UI', 'PingFang SC', 'Microsoft YaHei', sans-serif",
    '--display-font': "'Inter', -apple-system, 'Segoe UI', 'PingFang SC', 'Microsoft YaHei', sans-serif",
    '--display-letter-spacing': '0',
    '--ascii-btn-font': "'JetBrains Mono', 'Cascadia Mono', 'Consolas', 'Menlo', monospace",
  },
  naiveOverrides: {
    common: {
      primaryColor: '#2563eb',
      primaryColorHover: '#3b82f6',
      primaryColorPressed: '#1d4ed8',
      borderRadius: '6px',
    },
    Dropdown: {
      fontSizeSmall: '13px',
      fontSizeMedium: '13px',
      optionHeightSmall: '26px',
      optionHeightMedium: '28px',
      optionPrefixWidthSmall: '10px',
      optionPrefixWidthMedium: '10px',
      optionIconPrefixWidthSmall: '24px',
      optionIconPrefixWidthMedium: '24px',
      optionSuffixWidthSmall: '10px',
      optionSuffixWidthMedium: '10px',
      optionIconSuffixWidthSmall: '24px',
      optionIconSuffixWidthMedium: '24px',
    },
    Button: {
      borderRadiusTiny: '4px',
      borderRadiusSmall: '6px',
      borderRadiusMedium: '6px',
    },
    Input: {
      borderRadius: '6px',
    },
    Select: {
      menuBoxShadow: '0 10px 15px rgba(0,0,0,0.08)',
    },
    Tag: {
      borderRadius: '4px',
    },
  },
}
