import type { ThemeDefinition } from '../types'

/**
 * OLED HUD — Cyberpunk 终端风格。单态暗色。
 */
export const oledHud: ThemeDefinition = {
  id: 'oled-hud',
  name: 'OLED HUD',
  description: 'Cyberpunk 终端风格，OLED 暗色 + 霓虹绿/青/琥珀',
  isDark: true,
  tokens: {
    '--bg': '#050508',
    '--bg-panel': '#0A0A0F',
    '--bg-elevated': '#12121A',
    '--border': '#1E1E2E',
    '--text': '#E0E0E8',
    '--text-dim': '#7A8A9A',
    '--accent': '#00E676',
    '--accent-cyan': '#00D4FF',
    '--accent-teal': '#00E676',
    '--accent-violet': '#B388FF',
    '--ok': '#00E676',
    '--warn': '#FFB000',
    '--err': '#FF3366',
    '--rx-bg': 'rgba(0,212,255,0.08)',
    '--rx-border': 'rgba(0,212,255,0.30)',
    '--rx-text': '#E0E0E8',
    '--tx-bg': 'rgba(255,176,0,0.08)',
    '--tx-border': 'rgba(255,176,0,0.30)',
    '--tx-text': '#E0E0E8',
    '--glass-bg': '#0A0A0F',
    '--glass-border': '#1E1E2E',
    '--glass-highlight': '#00E676',
    '--glass-blur': '0px',
    '--glass-blur-sm': '0px',
    '--shadow-sm': '0 1px 3px rgba(0,0,0,0.5)',
    '--shadow-md': '0 4px 12px rgba(0,0,0,0.5)',
    '--shadow-lg': '0 8px 24px rgba(0,0,0,0.6)',
    '--radius': '2px',
    '--radius-sm': '2px',
    '--radius-md': '2px',
    '--radius-lg': '3px',
    '--radius-xl': '4px',
    '--pill-radius': '999px',
    '--border-width': '1px',
    '--chat-bg': 'var(--bg-panel)', // 0 blur 不透明底（与透出 --glass-bg 一致）
    '--gap': '8px',
    '--mono-font': "'JetBrains Mono','Cascadia Mono','Consolas',monospace",
    '--ui-font': "'Inter',-apple-system,'Segoe UI','PingFang SC','Microsoft YaHei',sans-serif",
    '--display-font': "'Orbitron Local','Orbitron','Inter',sans-serif",
    '--display-letter-spacing': '0.4px',
    '--ascii-btn-font': "'Orbitron Local','Orbitron','Inter',sans-serif",
    '--search-highlight-bg': '#1A3D1A',
    '--search-highlight-text': '#00FF88',
    '--search-active-bg': '#2D5A1E',
    '--search-active-text': '#00FF88',
  },
  // 终端视口：HUD 霓虹色系（绿/青/琥珀/品红）灌入 ANSI，纯 OLED 黑底
  terminal: {
    background: '#0A0A0F',
    foreground: '#E0E0E8',
    cursor: '#00E676',
    cursorAccent: '#050508',
    selectionBackground: 'rgba(0, 230, 118, 0.28)',
    black: '#1E1E2E',
    red: '#FF3366',
    green: '#00E676',
    yellow: '#FFB000',
    blue: '#3D7BFF',
    magenta: '#B388FF',
    cyan: '#00D4FF',
    white: '#9AA5B8',
    brightBlack: '#5A6A7A',
    brightRed: '#FF6690',
    brightGreen: '#66FFA6',
    brightYellow: '#FFC94D',
    brightBlue: '#7DA2FF',
    brightMagenta: '#D0B3FF',
    brightCyan: '#66E3FF',
    brightWhite: '#F0F0F8',
  },
  naiveOverrides: {
    common: {
      primaryColor: '#00E676',
      primaryColorHover: '#33FF99',
      primaryColorPressed: '#00C853',
      borderRadius: '2px',
      fontFamily: 'var(--ui-font)',
    },
    Dropdown: {
      fontSizeSmall: '13px',
      fontSizeMedium: '13px',
      optionHeightSmall: '26px',
      optionHeightMedium: '28px',
      optionPrefixWidthSmall: '10px',
      optionPrefixWidthMedium: '10px',
      optionIconPrefixWidthSmall: '24px',
      optionIconPrefixWidthMedium: '24px',
      optionSuffixWidthSmall: '10px',
      optionSuffixWidthMedium: '10px',
      optionIconSuffixWidthSmall: '24px',
      optionIconSuffixWidthMedium: '24px',
    },
    Button: {
      borderRadiusTiny: '2px',
      borderRadiusSmall: '2px',
      borderRadiusMedium: '2px',
    },
    Input: {
      borderRadius: '2px',
    },
    Select: {
      menuBoxShadow: '0 4px 12px rgba(0,0,0,0.5)',
    },
    Tag: {
      borderRadius: '2px',
    },
  },
}
