export { register, getTheme, listThemes, applyTokens, applyTheme, applyFonts } from '@/themes/registry'
export { resolveTerminalPalette } from '@/themes/terminal'
export { migrateLegacyThemeFields } from '@/themes/migrate'
export type { ThemeDefinition, ThemeTokens, TokenKey, TerminalPalette } from '@/themes/types'
export { TOKEN_KEYS, TERMINAL_PALETTE_KEYS } from '@/themes/types'
