export { register, getTheme, listThemes, applyTokens, applyTheme, applyFonts } from './registry'
export { resolveTerminalPalette } from './terminal'
export { migrateLegacyThemeFields } from './migrate'
export type { ThemeDefinition, ThemeTokens, TokenKey, TerminalPalette } from './types'
export { TOKEN_KEYS, TERMINAL_PALETTE_KEYS } from './types'
